# Generated by Django 5.2.1 on 2025-06-08 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_unlockedpillar'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='frequency',
            field=models.CharField(blank=True, choices=[('global', 'Global'), ('daily', 'Diaria'), ('weekly', 'Semanal'), (None, 'Sin frecuencia')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='declaration',
            name='pillar',
            field=models.CharField(choices=[('Vision', 'Visiรณn'), ('Proposito', 'Propรณsito'), ('Creencias', 'Creencias'), ('Estrategias', 'Estrategias')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.module'),
        ),
    ]
