# Generated by Django 5.2.1 on 2025-06-09 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mission_frequency_alter_declaration_pillar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComfortWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp_actual', models.PositiveIntegerField(default=100)),
                ('hp_max', models.PositiveIntegerField(default=100)),
                ('nivel_muro', models.PositiveIntegerField(default=1)),
                ('fecha_ultimo_ataque', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('dificultad', models.CharField(choices=[('fácil', 'Fácil'), ('media', 'Media'), ('difícil', 'Difícil')], max_length=16)),
                ('horario_sugerido', models.TimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('dias_activos', models.PositiveIntegerField(default=0)),
                ('estrellas', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('nivel', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('incubando', 'Incubando'), ('inactivo', 'Inactivo')], default='incubando', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
