# Generated by Django 5.2.1 on 2025-06-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mission_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='auto_unlocked',
            field=models.BooleanField(default=False),
        ),
    ]
