# Generated by Django 5.2.1 on 2025-06-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_moduleprogress_auto_unlocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
