# Generated by Django 5.2.1 on 2025-06-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_leveltitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comfortwall',
            name='hp_actual',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='comfortwall',
            name='hp_max',
            field=models.FloatField(default=100),
        ),
    ]
